image: docker:latest

variables:
  LALSUITE_DEV_REPOSITORY: 'igwn/lalsuite-dev'

stages:
  - docker
  - rebuild

docker:build:
  stage: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker logout $CI_REGISTRY
    - |
        # push to docker hub
        if [[ $CI_PROJECT_NAMESPACE == 'docker' ]]; then
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
          docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME $LALSUITE_DEV_REPOSITORY:$CI_COMMIT_REF_NAME
          docker push $LALSUITE_DEV_REPOSITORY:$CI_COMMIT_REF_NAME
          docker logout
        fi

#
# trigger rebuilds of downstream containers
#

# lalsuite-dev-clang

rebuild:lalsuite-dev-clang:7:
  stage: rebuild
  only:
    - branches@docker/lalsuite-dev
  trigger:
    project: docker/lalsuite-dev-clang
    branch: '7'

rebuild:lalsuite-dev-clang:8:
  stage: rebuild
  only:
    - branches@docker/lalsuite-dev
  trigger:
    project: docker/lalsuite-dev-clang
    branch: '8'

rebuild:lalsuite-dev-clang:9:
  stage: rebuild
  only:
    - branches@docker/lalsuite-dev
  trigger:
    project: docker/lalsuite-dev-clang
    branch: '9'

rebuild:lalsuite-dev-clang:dev:
  stage: rebuild
  only:
    - branches@docker/lalsuite-dev
  trigger:
    project: docker/lalsuite-dev-clang
    branch: dev